import type { AcervoContent } from "../../../../lib/content-types";

export const acervoContent: AcervoContent = {
  hero: {
    searchLabel: "Buscar",
    searchPlaceholder: "Buscar por título, tag ou cidade…",
    emptyStateMessage: "Nenhum resultado para sua busca. Ajuste filtros ou termos.",
    filters: {
      types: ["Todos", "Documento", "Depoimento", "Bibliografia", "Jornal", "Foto"],
      origins: ["Todos", "Volta Redonda", "Barra Mansa", "Fundos"],
      tags: [
        "Documentos",
        "Atas",
        "Greves",
        "Depoimentos",
        "Oral",
        "Lideranças",
        "Bibliografia",
        "Clipping",
        "Jornais",
        "Histórico",
        "Fotografia",
        "Cotidiano",
        "Mobilização",
        "Fundos",
        "Const. Civil",
        "Metalúrgico",
        "Mov. Populares",
        "Dom Waldyr",
      ],
    },
    items: [
      {
        title: "Documentos – Volta Redonda",
        origin: "Volta Redonda",
        type: "Documento",
        date: "1952-03-10",
        tags: ["Documentos", "Atas", "Greves"],
        href: "/acervo/volta-redonda/documentos",
      },
      {
        title: "Depoimentos – Volta Redonda",
        origin: "Volta Redonda",
        type: "Depoimento",
        date: "1983-11-02",
        tags: ["Depoimentos", "Oral", "Lideranças"],
        href: "/acervo/volta-redonda/depoimentos",
      },
      {
        title: "Referência Bibliográfica – Volta Redonda",
        origin: "Volta Redonda",
        type: "Bibliografia",
        date: "1980-01-01",
        tags: ["Bibliografia", "Clipping"],
        href: "/acervo/volta-redonda/referencia-bibliografica",
      },
      {
        title: "Jornais de época – Volta Redonda",
        origin: "Volta Redonda",
        type: "Jornal",
        date: "1953-07-05",
        tags: ["Jornais", "Greves"],
        href: "/acervo/volta-redonda/jornais-de-epoca",
      },
      {
        title: "Acervo Fotográfico – Volta Redonda",
        origin: "Volta Redonda",
        type: "Foto",
        date: "1948-06-01",
        tags: ["Fotografia", "Cotidiano"],
        href: "/acervo/volta-redonda/acervo-fotografico",
      },
      {
        title: "Documentos – Barra Mansa",
        origin: "Barra Mansa",
        type: "Documento",
        date: "1958-02-09",
        tags: ["Documentos", "Atas"],
        href: "/acervo/barra-mansa/documentos",
      },
      {
        title: "Depoimentos – Barra Mansa",
        origin: "Barra Mansa",
        type: "Depoimento",
        date: "1978-06-15",
        tags: ["Depoimentos", "Oral"],
        href: "/acervo/barra-mansa/depoimentos",
      },
      {
        title: "Referência Bibliográfica – Barra Mansa",
        origin: "Barra Mansa",
        type: "Bibliografia",
        date: "1985-01-01",
        tags: ["Bibliografia", "Clipping"],
        href: "/acervo/barra-mansa/referencia-bibliografica",
      },
      {
        title: "Jornais de época – Barra Mansa",
        origin: "Barra Mansa",
        type: "Jornal",
        date: "1937-07-17",
        tags: ["Jornais", "Histórico"],
        href: "/acervo/barra-mansa/jornais-de-epoca",
      },
      {
        title: "Acervo Fotográfico – Barra Mansa",
        origin: "Barra Mansa",
        type: "Foto",
        date: "1950-01-01",
        tags: ["Fotografia", "Mobilização"],
        href: "/acervo/barra-mansa/acervo-fotografico",
      },
      {
        title: "Fundos – Construção Civil",
        origin: "Fundos",
        type: "Documento",
        date: "1965-12-20",
        tags: ["Fundos", "Const. Civil"],
        href: "/acervo/fundos/const-civil",
      },
      {
        title: "Fundos – Metalúrgico",
        origin: "Fundos",
        type: "Documento",
        date: "1960-06-01",
        tags: ["Fundos", "Metalúrgico"],
        href: "/acervo/fundos/metalurgico",
      },
      {
        title: "Fundos – Movimentos Populares",
        origin: "Fundos",
        type: "Jornal",
        date: "1979-04-20",
        tags: ["Fundos", "Mov. Populares", "Cartazes"],
        href: "/acervo/fundos/mov-operario",
      },
      {
        title: "Fundos – Dom Waldyr",
        origin: "Fundos",
        type: "Bibliografia",
        date: "1988-10-05",
        tags: ["Fundos", "Dom Waldyr"],
        href: "/acervo/fundos/dom-waldyr",
      },
    ],
  },
  cityShowcase: {
    eyebrow: "Acervo por fundo",
    title: "Fundo Dom Waldyr",
    description:
      "Neste momento o acervo publico destaca o fundo Dom Waldyr com suas principais frentes de pesquisa e acesso.",
    badges: [
      { label: "Jornais", icon: "newspaper" },
      { label: "Fotos", icon: "photo" },
      { label: "Documentos & Bibliografia", icon: "documents" },
    ],
    cities: [
      {
        name: "Dom Waldyr",
        description: "Acervo relacionado a atuacao de Dom Waldyr.",
        coverage: "Serie documental | Documentos, imprensa, iconografia",
        focus: ["Dom Waldyr"],
        image: "/hero.png",
        sections: [
          {
            title: "Dom Waldyr",
            description: "Acervo relacionado a atuacao de Dom Waldyr.",
            href: "/acervo/fundos/dom-waldyr",
            thumb: "/globe.svg",
          },
        ],
      },
    ],
  },
};
