import type { AcervoContent } from "../../../../lib/content-types";

export const acervoContent: AcervoContent = {
  hero: {
    searchLabel: "Buscar",
    searchPlaceholder: "Buscar por título, tag ou cidade…",
    emptyStateMessage: "Nenhum resultado para sua busca. Ajuste filtros ou termos.",
    filters: {
      types: ["Todos", "Documento", "Depoimento", "Bibliografia", "Jornal", "Foto"],
      origins: ["Todos", "Volta Redonda", "Barra Mansa", "Fundos"],
      tags: [
        "Documentos",
        "Atas",
        "Greves",
        "Depoimentos",
        "Oral",
        "Lideranças",
        "Bibliografia",
        "Clipping",
        "Jornais",
        "Histórico",
        "Fotografia",
        "Cotidiano",
        "Mobilização",
        "Fundos",
        "Const. Civil",
        "Metalúrgico",
        "Mov. Populares",
        "Dom Waldyr",
      ],
    },
    items: [
      {
        title: "Documentos – Volta Redonda",
        origin: "Volta Redonda",
        type: "Documento",
        date: "1952-03-10",
        tags: ["Documentos", "Atas", "Greves"],
        href: "/acervo/volta-redonda/documentos",
      },
      {
        title: "Depoimentos – Volta Redonda",
        origin: "Volta Redonda",
        type: "Depoimento",
        date: "1983-11-02",
        tags: ["Depoimentos", "Oral", "Lideranças"],
        href: "/acervo/volta-redonda/depoimentos",
      },
      {
        title: "Referência Bibliográfica – Volta Redonda",
        origin: "Volta Redonda",
        type: "Bibliografia",
        date: "1980-01-01",
        tags: ["Bibliografia", "Clipping"],
        href: "/acervo/volta-redonda/referencia-bibliografica",
      },
      {
        title: "Jornais de época – Volta Redonda",
        origin: "Volta Redonda",
        type: "Jornal",
        date: "1953-07-05",
        tags: ["Jornais", "Greves"],
        href: "/acervo/volta-redonda/jornais-de-epoca",
      },
      {
        title: "Acervo Fotográfico – Volta Redonda",
        origin: "Volta Redonda",
        type: "Foto",
        date: "1948-06-01",
        tags: ["Fotografia", "Cotidiano"],
        href: "/acervo/volta-redonda/acervo-fotografico",
      },
      {
        title: "Documentos – Barra Mansa",
        origin: "Barra Mansa",
        type: "Documento",
        date: "1958-02-09",
        tags: ["Documentos", "Atas"],
        href: "/acervo/barra-mansa/documentos",
      },
      {
        title: "Depoimentos – Barra Mansa",
        origin: "Barra Mansa",
        type: "Depoimento",
        date: "1978-06-15",
        tags: ["Depoimentos", "Oral"],
        href: "/acervo/barra-mansa/depoimentos",
      },
      {
        title: "Referência Bibliográfica – Barra Mansa",
        origin: "Barra Mansa",
        type: "Bibliografia",
        date: "1985-01-01",
        tags: ["Bibliografia", "Clipping"],
        href: "/acervo/barra-mansa/referencia-bibliografica",
      },
      {
        title: "Jornais de época – Barra Mansa",
        origin: "Barra Mansa",
        type: "Jornal",
        date: "1937-07-17",
        tags: ["Jornais", "Histórico"],
        href: "/acervo/barra-mansa/jornais-de-epoca",
      },
      {
        title: "Acervo Fotográfico – Barra Mansa",
        origin: "Barra Mansa",
        type: "Foto",
        date: "1950-01-01",
        tags: ["Fotografia", "Mobilização"],
        href: "/acervo/barra-mansa/acervo-fotografico",
      },
      {
        title: "Fundos – Construção Civil",
        origin: "Fundos",
        type: "Documento",
        date: "1965-12-20",
        tags: ["Fundos", "Const. Civil"],
        href: "/acervo/fundos/const-civil",
      },
      {
        title: "Fundos – Metalúrgico",
        origin: "Fundos",
        type: "Documento",
        date: "1960-06-01",
        tags: ["Fundos", "Metalúrgico"],
        href: "/acervo/fundos/metalurgico",
      },
      {
        title: "Fundos – Movimentos Populares",
        origin: "Fundos",
        type: "Jornal",
        date: "1979-04-20",
        tags: ["Fundos", "Mov. Populares", "Cartazes"],
        href: "/acervo/fundos/mov-operario",
      },
      {
        title: "Fundos – Dom Waldyr",
        origin: "Fundos",
        type: "Bibliografia",
        date: "1988-10-05",
        tags: ["Fundos", "Dom Waldyr"],
        href: "/acervo/fundos/dom-waldyr",
      },
    ],
  },
  cityShowcase: {
    eyebrow: "Acervo por cidade e fundos",
    title: "Visão completa dos núcleos disponíveis",
    description:
      "Neste momento o acervo público reúne duas cidades (Volta Redonda e Barra Mansa) e fundos temáticos. Cada bloco abaixo detalha o recorte, cobertura e pré-visualizações das seções principais.",
    badges: [
      { label: "Jornais", icon: "newspaper" },
      { label: "Fotos", icon: "photo" },
      { label: "Documentos & Bibliografia", icon: "documents" },
    ],
    cities: [
      {
        name: "Volta Redonda",
        description:
          "Eixo industrial com greves históricas, organização por seção e produção documental intensa ligada à construção civil e metalurgia.",
        coverage: "Anos 1940–2000 | Movimentos paredistas e cotidiano fabril",
        focus: ["Documentação sindical", "História oral", "Clippings e bibliografia", "Fotografia de mobilização"],
        image: "/hero.png",
        sections: [
          {
            title: "Documentos",
            description: "Atas, ofícios e relatórios das bases em VR.",
            href: "/acervo/volta-redonda/documentos",
            thumb: "/file.svg",
          },
          {
            title: "Depoimentos",
            description: "História oral com lideranças e chão de fábrica.",
            href: "/acervo/volta-redonda/depoimentos",
            thumb: "/hero.png",
          },
          {
            title: "Referência Bibliográfica",
            description: "Clippings, livros e artigos sobre VR.",
            href: "/acervo/volta-redonda/referencia-bibliografica",
            thumb: "/globe.svg",
          },
          {
            title: "Jornais de época",
            description: "Capas e edições digitalizadas.",
            href: "/acervo/volta-redonda/jornais-de-epoca",
            thumb: "/window.svg",
          },
          {
            title: "Acervo Fotográfico",
            description: "Mobilização e cotidiano fabril em imagens.",
            href: "/acervo/volta-redonda/acervo-fotografico",
            thumb: "/hero.png",
          },
        ],
      },
      {
        name: "Barra Mansa",
        description:
          "Redes regionais de apoio, organização por bairros e memória operária conectada ao Vale do Paraíba.",
        coverage: "Anos 1930–2000 | Bases locais, assembleias e cultura sindical",
        focus: ["Atas e ofícios", "Relatos de trabalhadores", "Recortes de imprensa", "Fotografia do território"],
        image: "/CUT.png",
        sections: [
          {
            title: "Documentos",
            description: "Ofícios, atas e normativas locais.",
            href: "/acervo/barra-mansa/documentos",
            thumb: "/file.svg",
          },
          {
            title: "Depoimentos",
            description: "Vozes de trabalhadores e dirigentes.",
            href: "/acervo/barra-mansa/depoimentos",
            thumb: "/hero.png",
          },
          {
            title: "Referência Bibliográfica",
            description: "Bibliografia e catálogos sobre BM.",
            href: "/acervo/barra-mansa/referencia-bibliografica",
            thumb: "/globe.svg",
          },
          {
            title: "Jornais de época",
            description: "Recortes e edições históricas.",
            href: "/acervo/barra-mansa/jornais-de-epoca",
            thumb: "/window.svg",
          },
          {
            title: "Acervo Fotográfico",
            description: "Imagens de mobilização e cotidiano.",
            href: "/acervo/barra-mansa/acervo-fotografico",
            thumb: "/hero.png",
          },
        ],
      },
      {
        name: "Fundos Temáticos",
        description:
          "Coleções organizadas por fundos institucionais e temáticos: construção civil, metalurgia, movimento operário e Dom Waldyr.",
        coverage: "Séries diversas | Documentos, imprensa, iconografia",
        focus: ["Const. Civil", "Metalúrgico", "Mov. Populares", "Dom Waldyr"],
        image: "/hero.png",
        sections: [
          {
            title: "Const. Civil",
            description: "Atas, memoriais e registros da categoria.",
            href: "/acervo/fundos/const-civil",
            thumb: "/file.svg",
          },
          {
            title: "Metalúrgico",
            description: "Documentação e mídia sindical da metalurgia.",
            href: "/acervo/fundos/metalurgico",
            thumb: "/file.svg",
          },
          {
            title: "Mov. Populares",
            description: "Cartazes, jornais e narrativas do movimento.",
            href: "/acervo/fundos/mov-operario",
            thumb: "/window.svg",
          },
          {
            title: "Dom Waldyr",
            description: "Acervo relacionado à atuação de Dom Waldyr.",
            href: "/acervo/fundos/dom-waldyr",
            thumb: "/globe.svg",
          },
        ],
      },
    ],
  },
};
