import type { BibliographyContent } from "../../../../lib/content-types";

export const productionContent: BibliographyContent = {
  hero: {
    eyebrow: "ProduÃ§Ã£o bibliogrÃ¡fica",
    title: "Pesquisa, relatos e publicaÃ§Ãµes",
    description: "Artigos, livros, relatÃ³rios e capÃ­tulos produzidos a partir do acervo e de parcerias institucionais.",
    cta: { label: "Acesso Ã  informaÃ§Ã£o", href: "/acesso-a-informacao" },
  },
  filters: {
    types: ["Artigo", "Livro", "RelatÃ³rio", "CapÃ­tulo", "InventÃ¡rio"],
    decades: ["2020s", "2010s", "2000s", "1990s", "1980s"],
    tags: [
      "MemÃ³ria OperÃ¡ria",
      "Trabalho",
      "Cidade",
      "Fotografia",
      "Sindicalismo",
      "HabitaÃ§Ã£o",
      "PolÃ­tica",
      "DigitalizaÃ§Ã£o",
      "PreservaÃ§Ã£o",
      "Metadados",
      "Boletins",
    ],
  },
  searchPlaceholder: "Buscar por título, autor ou palavra-chave",
  items: [
    {
      id: "a1",
      title: "MemÃ³ria operÃ¡ria e espaÃ§o urbano",
      authors: ["Rubem Machado", "Ana Bezerra"],
      year: 2021,
      type: "Artigo",
      decade: "2020s",
      tags: ["MemÃ³ria OperÃ¡ria", "Trabalho", "Cidade"],
      abstract: "AnÃ¡lise das relaÃ§Ãµes entre memÃ³ria operÃ¡ria, territÃ³rio e processos de urbanizaÃ§Ã£o no Vale do ParaÃ­ba.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/memoria-operaria-espaco-urbano",
      pdf: "/pdfs/memoria-operaria.pdf",
    },
    {
      id: "a2",
      title: "InventÃ¡rio do acervo fotogrÃ¡fico 1940â€“1970",
      authors: ["Marina Lopes"],
      year: 2020,
      type: "RelatÃ³rio",
      decade: "2020s",
      tags: ["Fotografia", "CatalogaÃ§Ã£o", "Acervo"],
      abstract: "Metodologia, critÃ©rios de descriÃ§Ã£o e resultados do inventÃ¡rio das fotografias histÃ³ricas.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/inventario-acervo-fotografico",
      pdf: "/pdfs/inventario-acervo.pdf",
    },
    {
      id: "a3",
      title: "Sindicalismo e habitaÃ§Ã£o popular",
      authors: ["Carlos Figueiredo"],
      year: 2017,
      type: "CapÃ­tulo",
      decade: "2010s",
      tags: ["Sindicalismo", "HabitaÃ§Ã£o", "PolÃ­tica"],
      abstract: "CapÃ­tulo que revisita experiÃªncias de organizaÃ§Ã£o por moradia e seus elos com o trabalho.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/sindicalismo-habitacao-popular",
      pdf: "#",
    },
    {
      id: "a4",
      title: "Guia de digitalizaÃ§Ã£o e restauraÃ§Ã£o",
      authors: ["Marina Lopes", "LÃ­via Rocha"],
      year: 2019,
      type: "Livro",
      decade: "2010s",
      tags: ["DigitalizaÃ§Ã£o", "RestauraÃ§Ã£o", "Metadados"],
      abstract: "Boas prÃ¡ticas, padrÃµes tÃ©cnicos e fluxos de preservaÃ§Ã£o digital para acervos histÃ³ricos.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/guia-digitalizacao",
      pdf: "/pdfs/guia-digitalizacao.pdf",
    },
    {
      id: "a5",
      title: "Boletins sindicais: uma leitura histÃ³rica",
      authors: ["Sofia Mendes"],
      year: 2012,
      type: "Artigo",
      decade: "2010s",
      tags: ["Boletins", "HistÃ³ria", "ComunicaÃ§Ã£o"],
      abstract: "AnÃ¡lise crÃ­tica de boletins sindicais como fonte primÃ¡ria para a histÃ³ria do trabalho.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/boletins-leitura-historica",
      pdf: "#",
    },
    {
      id: "a6",
      title: "Mapeamento de comissÃµes de fÃ¡brica (1960â€“1980)",
      authors: ["Rubem Machado"],
      year: 2015,
      type: "RelatÃ³rio",
      decade: "2010s",
      tags: ["ComissÃµes", "FÃ¡brica", "OrganizaÃ§Ã£o"],
      abstract: "Pesquisa documental sobre comissÃµes de fÃ¡brica, estruturas internas e pautas reivindicatÃ³rias.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1758821738/Manchete_6_de_fevereiro_de_1960_fh5bkv.jpg",
      href: "/producao-bibliografica/comissoes-fabrica-mapeamento",
      pdf: "/pdfs/comissoes-fabrica.pdf",
    },
  ],
  footnote: "Metadados e arquivos PDF estÃ£o em constante atualizaÃ§Ã£o. Consulte a pÃ¡gina de cada item para referÃªncia oficial.",
};
