import type { JournalsContent } from "../../../../lib/content-types";

export const journalsContent: JournalsContent = {
  hero: {
    eyebrow: "Jornais de época",
    title: "Uma janela para o passado",
    description: "Capas, pautas e narrativas sindicais digitalizadas para leitura confortável em qualquer dispositivo.",
    note: "Clique em uma capa para abrir o leitor em tela cheia e compartilhe o trecho mais relevante.",
  },
  searchPlaceholder: "Buscar por título, década ou palavra-chave",
  filterLabel: "Filtrar por década",
  decades: ["Todos", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s"],
  defaultCover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
  editions: [
    {
      slug: "o-operario-1913-05-12",
      title: "O Operário",
      date: "12/05/1913",
      decade: "1910s",
      summary: "Organização de base e pautas salariais do setor siderúrgico.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      full: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      width: 1359,
      height: 2998,
    },
    {
      slug: "folha-trabalhador-1921-09-03",
      title: "Folha do Trabalhador",
      date: "03/09/1921",
      decade: "1920s",
      summary: "Mobilizações urbanas e comissões de fábrica em pauta naquele ano.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      full: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      width: 1359,
      height: 2998,
    },
    {
      slug: "gazeta-sindical-1932-02-28",
      title: "Gazeta Sindical",
      date: "28/02/1932",
      decade: "1930s",
      summary: "Greves, assembleias e resistência em um período de intensas disputas.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      full: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      width: 1359,
      height: 2998,
    },
    {
      slug: "o-dia-do-povo-1937-07-17",
      title: "O Dia do Povo",
      date: "17/07/1937",
      decade: "1930s",
      summary: "Marchas, assembleias e o cotidiano dos trabalhadores em formação sindical.",
      cover: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      full: "https://res.cloudinary.com/dc7u5spia/image/upload/v1765237328/Jornal_do_Brasil_-_2%C2%AA_Auditoria_do_Ex%C3%A9rcito_xzf1q2.jpg",
      width: 1359,
      height: 2998,
    },
  ],
  footerNote: "Para reprodução e uso acadêmico, consulte o Acesso à Informação.",
};
